### ISSUE TITLE
Minor issue with language selection

### ISSUE THREAD

**Issue by elboletaire** [derivepass/derivepass-vue#25]
**Describe the bug**
Accessing the site with a browser set by default to languages not defined in the site, makes the language selector show the preferred browser language, although it does not exist in locales.

**To Reproduce**
1. You need your browser with the default language set to something different than English or Russian.
2. Open a private browsing tab to ensure you haven't set the language in the website.
3. Check out the language selector. 

**Expected behavior**
Show `en`, as it's the fallback language.

**Screenshots**

![imatge](https://user-images.githubusercontent.com/153305/52119779-8b532d00-261a-11e9-9d9e-289ae41af6a8.png)

**Desktop (please complete the following information):**
 - OS: Any (tried under Ubuntu Linux 18.04)
 - Browser: Any (tried with firefox and chrome).

**Comment by indutny** [comment]
Thank you! Should be fixed now.

**Comment by elboletaire** [comment]
Verified using the [now deployment link](https://derivepass-jrztnwd2s.now.sh/) and it works well now :smiley:

**Comment by indutny** [comment]
:+1:

**Comment by indutny** [comment]
Thank you!
