### ISSUE TITLE
Webpage asks if you really want to leave when staying too much in the add application page

### ISSUE THREAD

**Issue by elboletaire** [derivepass/derivepass-vue#27]
**Describe the bug**

The `leave` message in application is being showed after the logout timeout has passed.

**To Reproduce**
1. Access using your master password
2. Click on Add Application
3. Write something in any field, to ensure the app will ask you if you really wanna leave.
4. Wait 3 minutes until the app asks you if you really wanna leave.

PS: it's recommended to decrease the `LOGOUT_TIMEOUT` so you don't need to wait that three minutes (like I did the first time to ensure :sweat_smile:)

**Expected behavior**

Well it's a bit difficult this one. The easiest way would be to simply not ask the user in this case.

Although the proper UX way may be asking if they really want to leave, and in case they ain't leaving, ask for the Master Password to unlock the storage. Because AFAIK, if you click on "no" to stay in the page, you won't be able to save anything because the Master Password is currently locked.

**Screenshots**

![image](https://user-images.githubusercontent.com/153305/52168034-dc4f4800-2724-11e9-8552-045502ad4b91.png)

**Desktop (please complete the following information):**

Doesn't matter in this case :)

**Smartphone (please complete the following information):**

Same :)

**Additional context**

Found it the first time while translating :stuck_out_tongue:

**Comment by indutny** [comment]
Thank you! Should be fixed now.
