### ISSUE TITLE
derivepass used as iOS homescreen web app can't access camera

### ISSUE THREAD

**Issue by Gozala** [derivepass/derivepass-vue#29]
**Describe the bug**
If you attempt to sync derivepass added as iOS homescreet web app it will fail with a following message "Error: Video recording is not supported by the browser" 

**To Reproduce**

1. Go to http://derivepass.com/ on iOS Safari
2. Click "Share" button and choose "Add to Home Screen" (in bottom row).
3. Launch DerivePass from homescreen
4. Go to "Settings"
5. Click "Receive" button under "QR Sync".
6. See error: `Error: Video recording is not supported by the browser`

**Expected behavior**
derivepass should enter "Start Receiving" mode.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.1.4
 - Browser Home screen app

**Additional context**
I found relevant thread on stackoverflow https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app and it appears to me that to make home screen web app capable of camera access needs to include

```
<meta name="apple-mobile-web-app-capable" content="yes">
```
From what I can tell (by searching the source code) currently that meta tag is missing. Apple also mentions that meta tag but nothing about camera so I'm not entirely sure:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by indutny** [comment]
This is unlikely to help, but I pushed the relevant change. I think it is a limitation of iOS that is going to be fixed in their next release.

**Comment by indutny** [comment]
Deployed to derivepass.com
