### ISSUE TITLE
Minor: html is being rendered as string for translations

### ISSUE THREAD

**Issue by elboletaire** [derivepass/derivepass-vue#32]
While opening #31 I realized that the html code added to translations is being rendered as plain strings now:

![imatge](https://user-images.githubusercontent.com/153305/55908024-9dcc8280-5bd8-11e9-9fbb-62a917350388.png)

Note the `<b>can</b>` and `<b>must</b>`.

This happens on all languages.

**Comment by indutny** [comment]
Oh no! Thanks for reporting this.
