### ISSUE TITLE
QR Keys are available even with session closed

### ISSUE THREAD

**Issue by elboletaire** [derivepass/derivepass-vue#33]
**Describe the bug**

QR Sync is available even having the session closed.

**To Reproduce**

Note that I've not tried to reproduce it, I'll do it now; but I thought this is urgent enough to be notified even without having all the information.

I've just clicked on configuration/QR/send, and there are all my QR keys, updated.

**Expected behavior**

To properly secure this information

**Screenshots**

![imatge](https://user-images.githubusercontent.com/153305/56084100-67884080-5e2e-11e9-9d1b-54d823f03c02.png)

**Comment by elboletaire** [comment]
Confirmed: I've just opened a private session, created an app, logged out.. went to configuration, send QR passwords, and there are the QR images:

![imatge](https://user-images.githubusercontent.com/153305/56084116-b209bd00-5e2e-11e9-8461-b581923e8900.png)
![imatge](https://user-images.githubusercontent.com/153305/56084117-b9c96180-5e2e-11e9-9145-1d239f77a6a5.png)

**Comment by elboletaire** [comment]
Maybe I'm wrong and this is an expected behavior and does not happen anything unless the person who copies this passwords knows my master key? Anyway, still seems a bit weird to me to be able to export all the data without the session open...

**Comment by indutny** [comment]
This might seem confusing, but all those records are actually encrypted with AES-256. The idea is that you might have several master passwords and QR sync would synchronize all of the applications associated to each of the passwords.

Does this make sense?

**Comment by elboletaire** [comment]
Yeah, I thought it a bit late :)

**Comment by indutny** [comment]
Cool!
