### ISSUE TITLE
iCloud Sync /  Authentication Error

### ISSUE THREAD

**Issue by Gozala** [derivepass/derivepass-vue#37]
**Describe the bug**
Attempt to enable iCloud Sync fails due to Authentication Error even though it should not.

**To Reproduce**
1. Go to https://derivepass.com/settings
2. Click on "iCloud Sync > Enable"
3. Click on ""iCloud Sync > Sign In"
4. Do Apple authentication in the popup window

**Expected behavior**
To get iCloud Sync enabled.

**Screenshots**
<img width="908" alt="image" src="https://user-images.githubusercontent.com/21236/64461671-ab683480-d0b2-11e9-9ba7-4c362e323c11.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Mojave 10.14.6 (18G87)
 - Browser [e.g. chrome, safari] Firefox Nightly 71.0a1 (2019-09-06)
 - Version [e.g. 22] `source code @ 1.2.1`

**Comment by Gozala** [comment]
I'm observing exact same issue with Safari on iOS

**Comment by elboletaire** [comment]
I had this issue before, but only if the "iCloud sync" option was previously shown without being logged in (which gives and authentication issue probably due to a different signature than expected).

I'm not sure if they both are related, but the error was pretty the same, visually at least.

**Comment by indutny** [comment]
I think this could be a problem with Apple's CSP. XHR to `https://setup.apple-cloudkit.com/setup/ws/1/oauth/validateToken` is blocked when requested from `https://cdn.apple-cloudkit.com/ck-auth/`

**Comment by indutny** [comment]
Which is `default-src 'none'; script-src blob: 'self' 'unsafe-inline' 'unsafe-eval' *.apple.com *.cdn-apple.com *.apple-mapkit.com *.apple-cloudkit.com *.apple-livephotoskit.com; style-src 'self' data: 'unsafe-inline' *.icloud.com *.apple.com *.cdn-apple.com; img-src 'self' blob: data: icloud.com *.icloud.com *.apple.com *.cdn-apple.com *.icloud-content.com *.apple-mapkit.com; media-src 'self' blob: data: *.icloud.com *.apple.com *.cdn-apple.com *.icloud-content.com; font-src 'self' blob: data: *.apple.com *.cdn-apple.com; connect-src blob: 'self' icloud.com *.icloud.com *.apple.com *.cdn-apple.com *.icloud-content.com *.apple-mapkit.com; frame-src 'self' blob: mailto: tel: *.icloud.com *.apple.com *.icloud-sandbox.com *.icloud-content.com; frame-ancestors 'self' *.icloud.com *.apple.com; form-action 'self' *.icloud.com; child-src blob: 'self'; base-uri 'self' *.icloud.com *.cdn-apple.com; report-uri https://feedbackws.icloud.com/reportRaw`

**Comment by elboletaire** [comment]
> I had this issue before, but only if the "iCloud sync" option was previously shown without being logged in (which gives and authentication issue probably due to a different signature than expected).

I'm just realizing that this issue cannot be reproduced, as of now, everything related to iCloud sync will surround the issue shown by @Gozala.

I hope we find a fix soon; right now I can't use derivepass (I have no data and cannot iCloud sync).

**Comment by elboletaire** [comment]
Apparently Apple fixed this on their side. Or at least it's working for me under linux (using firefox) and iOS (using safari).

**Comment by indutny** [comment]
Hooray!
